# Generated by Django 5.2.3 on 2025-06-21 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('HOD', 'Head of Department'), ('SECRETARY', 'Secretary'), ('REGULAR', 'Regular')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='find_my_lecturer_app.college')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('office_number', models.CharField(max_length=20)),
                ('building', models.CharField(max_length=100)),
                ('floor', models.PositiveSmallIntegerField()),
                ('office_type', models.CharField(max_length=30)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='find_my_lecturer_app.college')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='find_my_lecturer_app.department')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='find_my_lecturer_app.office')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='find_my_lecturer_app.department')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_roles', to='find_my_lecturer_app.lecturer')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to='find_my_lecturer_app.role')),
            ],
            options={
                'verbose_name': 'Department Role Assignment',
                'verbose_name_plural': 'Department Role Assignments',
                'unique_together': {('department', 'role')},
            },
        ),
    ]
