# Generated by Django 5.2.3 on 2025-06-21 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_my_lecturer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='college',
            table='College',
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AlterModelTable(
            name='departmentassignment',
            table='DepartmentAssignment',
        ),
        migrations.AlterModelTable(
            name='lecturer',
            table='Lecturer',
        ),
        migrations.AlterModelTable(
            name='office',
            table='Office',
        ),
        migrations.AlterModelTable(
            name='role',
            table='Role',
        ),
    ]
