# Generated by Django 5.2.3 on 2025-06-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_my_lecturer_app', '0002_alter_college_table_alter_department_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='building',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='office',
            name='college',
        ),
        migrations.RemoveField(
            model_name='office',
            name='office_type',
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_as_hod', to='find_my_lecturer_app.lecturer'),
        ),
        migrations.AddField(
            model_name='department',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_as_secretary', to='find_my_lecturer_app.lecturer'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='role',
            field=models.CharField(choices=[('LECTURER', 'Lecturer'), ('HOD', 'Head of Department'), ('SECRETARY', 'Secretary')], default='LECTURER', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturer',
            name='type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('CUBICLE', 'Cubicle'), ('LABORATORY', 'Laboratory')], default='STANDARD', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('CUBICLE', 'Cubicle'), ('LABORATORY', 'Laboratory')], default='STANDARD', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='office',
            name='office_number',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='DepartmentAssignment',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
