# Generated by Django 5.2.3 on 2025-06-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_my_lecturer_app', '0003_rename_building_office_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='type',
        ),
    ]
