# Generated by Django 5.2.3 on 2025-06-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_my_lecturer_app', '0004_remove_lecturer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HODLecturer',
            fields=[
                ('hod_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('lecturer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hod_record', to='find_my_lecturer_app.lecturer')),
            ],
            options={
                'db_table': 'HODLecturer',
            },
        ),
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='find_my_lecturer_app.hodlecturer'),
        ),
        migrations.CreateModel(
            name='SecretaryLecturer',
            fields=[
                ('secretary_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('lecturer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='secretary_record', to='find_my_lecturer_app.lecturer')),
            ],
            options={
                'db_table': 'SecretaryLecturer',
            },
        ),
        migrations.AlterField(
            model_name='department',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='find_my_lecturer_app.secretarylecturer'),
        ),
    ]
